<?php


use App\Models\ObraSocial;

use Carbon\Carbon;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\Hash;

class ObraSocialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {




     

      //                    EMPRESA                     //



      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL  DE EMPRESARIOS, PROFESIONALES Y MONOTRIBUTISTAS                                                                                                                                            ', 'siglas' => 'OSDEPYM           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL  EMPLEADOS DE AGENCIAS DE INFORMES                                                                                                                                                          ', 'siglas' => 'OSEADI            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL ACCION SOCIAL DE EMPRESARIOS                                                                                                                                                                ', 'siglas' => 'ASE               ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL ACEROS PARANA                                                                                                                                                                               ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL ASOCIACION DEL PERSONAL SUPERIOR DE LA ORGANIZACION TECHINT                                                                                                                                 ', 'siglas' => 'APSOT             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL ASOCIACION MUTUAL METALURGICA VILLA CONSTITUCION                                                                                                                                            ', 'siglas' => 'OSAMMVC           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL BANCARIA ARGENTINA                                                                                                                                                                          ', 'siglas' => 'OSBA              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL CABOT ARGENTINA                                                                                                                                                                             ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL CERAS JOHNSON                                                                                                                                                                               ', 'siglas' => 'JOHNSON           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL COOPERATIVA LTDA.  DE ASISTENCIA MEDICA ,FARMACEUTICA,CREDITO, Y CONSUMO DEL PERSONAL SUPERIOR DE LA INDUSTRIA DEL CAUCHO Y OTRAS ACTIVIDADES   INDUSTRIALES                                ', 'siglas' => 'CAMPSIC           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE  EMPLEADOS DE LA INDUSTRIA DEL VIDRIO                                                                                                                                                    ', 'siglas' => 'OSEIV             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE  LAS ASOCIACIONES DE EMPLEADOS DE FARMACIA                                                                                                                                               ', 'siglas' => 'OSADEF            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE ACTORES                                                                                                                                                                                  ', 'siglas' => 'OSA               ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE AERONAVEGANTES                                                                                                                                                                           ', 'siglas' => 'OSA               ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE AGENTES DE LOTERIAS Y AFINES DE LA REPUBLICA  ARGENTINA                                                                                                                                  ', 'siglas' => 'OSALARA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE CORDOBA                                                                                                                                                  ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE ENTRE RIOS                                                                                                                                               ', 'siglas' => 'OSAPMER           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE LA REPUBLICA ARGENTINA                                                                                                                                   ', 'siglas' => 'OSAPM             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE AGENTES DE PROPAGANDA MEDICA DE ROSARIO                                                                                                                                                  ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE ALFAJOREROS, REPOSTEROS, PIZZEROS Y HELADEROS                                                                                                                                            ', 'siglas' => 'OSARPYH           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE ARBITROS DEPORTIVOS DE LA REPUBLICA ARGENTINA                                                                                                                                            ', 'siglas' => 'OSADRA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE BOXEADORES AGREMIADOS DE LA REPUBLICA ARGENTINA                                                                                                                                          ', 'siglas' => 'OSBARA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE CAPATACES  ESTIBADORES PORTUARIOS                                                                                                                                                        ', 'siglas' => 'OSCEP             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE CAPITANES BAQUEANOS FLUVIALES DE LA MARINA MERCANTE                                                                                                                                      ', 'siglas' => 'OSCAPBAQFLU       ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE CAPITANES DE ULTRAMAR Y OFICIALES DE LA MARINA MERCANTE                                                                                                                                  ', 'siglas' => 'OSCOMM            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE CAPITANES, PILOTOS Y PATRONES DE PESCA                                                                                                                                                   ', 'siglas' => 'OSPESCA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE CERAMISTAS                                                                                                                                                                               ', 'siglas' => 'OSCE              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE COMISARIOS NAVALES                                                                                                                                                                       ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE CONDUCTORES CAMIONEROS Y PERSONAL DEL TRANSPORTE AUTOMOTOR DE CARGAS                                                                                                                     ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE CONDUCTORES DE REMISES Y AUTOS AL INSTANTE Y AFINES                                                                                                                                      ', 'siglas' => 'OSCRAIA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE CONDUCTORES NAVALES                                                                                                                                                                      ', 'siglas' => 'OSCONARA          ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE DIRECCION OSDO                                                                                                                                                                           ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE DOCENTES PARTICULARES                                                                                                                                                                    ', 'siglas' => 'OSDOP             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE EJECUTIVOS Y DEL PERSONAL DE DIRECCION DE EMPRESAS                                                                                                                                       ', 'siglas' => 'OSDE              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE EMPLEADOS DE DESPACHANTES DE ADUANA                                                                                                                                                      ', 'siglas' => 'OSEDA             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE EMPLEADOS DE LA MARINA MERCANTE                                                                                                                                                          ', 'siglas' => 'OSEMM             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE EMPLEADOS DE PRENSA DE CORDOBA                                                                                                                                                           ', 'siglas' => 'OSEPC             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE EMPLEADOS DEL TABACO                                                                                                                                                                     ', 'siglas' => 'OSETRA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE EMPLEADOS TEXTILES Y AFINES                                                                                                                                                              ', 'siglas' => 'OSETYA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE EMPLEADOS Y PERSONAL JERARQUICO  DE LA ACTIVIDAD DEL  NEUMATICO ARGENTINO DE NEUMATICOS GOOD YEAR SRL                                                                                    ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE ENCARGADOS APUNTADORES MARITIMOS                                                                                                                                                         ', 'siglas' => 'OSEAM             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE FOTOGRAFOS                                                                                                                                                                               ', 'siglas' => 'OSFOT             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE FUTBOLISTAS                                                                                                                                                                              ', 'siglas' => 'FAA               ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE GUINCHEROS Y MAQUINISTAS DE GRUAS MOVILES                                                                                                                                                ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE JARDINEROS, PARQUISTAS, VIVERISTAS Y FLORICULTORES DE LA REPUBLICA ARGENTINA                                                                                                             ', 'siglas' => 'OSJPVYF           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE JEFES Y OFICIALES MAQUINISTAS NAVALES                                                                                                                                                    ', 'siglas' => 'OSJOMN            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE JEFES Y OFICIALES NAVALES DE RADIOCOMUNICACIONES                                                                                                                                         ', 'siglas' => 'OSJONR            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA ACTIVIDAD DE SEGUROS, REASEGUROS, CAPITALIZACION Y AHORRO Y PRESTAMO PARA LA VIVIENDA                                                                                                 ', 'siglas' => 'OSSEG             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA ACTIVIDAD MINERA                                                                                                                                                                      ', 'siglas' => 'O.S.A.M.          ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA ASOCIACION CIVIL PROSINDICATO DE AMAS DE CASA DE LA REPUBLICA ARGENTINA                                                                                                               ', 'siglas' => 'OSSACRA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA CAMARA DE EMPRESARIOS DE AGENCIAS DE REMISES DE LA PROVINCIA DE BUENOS AIRES                                                                                                          ', 'siglas' => 'O.S.C.E.A.R.B.A.  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA CONFEDERACION DE OBREROS Y EMPLEADOS MUNICIPALES  ARGENTINA ( OSCOEMA )                                                                                                               ', 'siglas' => 'OSCOEMA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA FEDERACION ARGENTINA DE TRABAJADORES DE LUZ Y FUERZA                                                                                                                                  ', 'siglas' => 'OSFATLYF          ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA FEDERACION ARGENTINA DEL TRABAJADOR  DE LAS UNIVERSIDADES NACIONALES                                                                                                                  ', 'siglas' => 'OSFATUN           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA FEDERACION DE CAMARAS Y CENTROS COMERCIALES ZONALES DE LA REPUBLICA ARGENTINA (FEDECAMARAS)                                                                                           ', 'siglas' => 'FEDECAMARAS       ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA FEDERACION GREMIAL DE LA INDUSTRIA DE LA CARNE Y SUS DERIVADOS                                                                                                                        ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA INDUSTRIA DEL TRANSPORTE  AUTOMOTOR DE CORDOBA                                                                                                                                        ', 'siglas' => 'OSITAC            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LA UNION OBRERA METALURGICA DE LA REPUBLICA ARGENTINA                                                                                                                                    ', 'siglas' => 'OSUOMRA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOCUTORES                                                                                                                                                                                ', 'siglas' => 'OSDEL             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOS  LEGISLADORES DE LA REPUBLICA ARGENTINA                                                                                                                                              ', 'siglas' => 'OSLERA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOS  SUPERVISORES DE LA INDUSTRIA METALMECANICA DE LA REPUBLICA ARGENTINA                                                                                                                ', 'siglas' => 'OSSIMRA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOS CORTADORES DE LA INDUMENTARIA                                                                                                                                                        ', 'siglas' => 'OSUCI             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOS EMPLEADOS DE COMERCIO Y ACTIVIDADES CIVILES                                                                                                                                          ', 'siglas' => 'OSECAC            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOS MEDICOS DE LA CIUDAD DE BUENOS AIRES                                                                                                                                                 ', 'siglas' => 'OSMEDICA          ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOS PROFESIONALES UNIVERSITARIOS DEL AGUA Y LA ENERGIA ELECTRICA                                                                                                                         ', 'siglas' => 'OSPUAYE           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOS TRABAJADORES ASOCIADOS A LA ASOCIACION MUTUAL MERCANTIL ARGENTINA                                                                                                                    ', 'siglas' => 'OSTAMMA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOS TRABAJADORES DE LA CARNE Y AFINES DE LA REPUBLICA ARGENTINA                                                                                                                          ', 'siglas' => 'O.S.T.C.A.R.A.    ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE LOS TRABAJADORES DE LAS EMPRESAS DE ELECTRICIDAD                                                                                                                                         ', 'siglas' => 'OSTEE             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE MANDOS MEDIOS DE TELECOMUNICACIONES EN LA REPUBLICA ARGENTINA Y MERCOSUR                                                                                                                 ', 'siglas' => 'OSMMEDT           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE MAQUINISTAS DE TEATRO Y TELEVISION                                                                                                                                                       ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE MINISTROS, SECRETARIOS Y SUBSECRETARIOS                                                                                                                                                  ', 'siglas' => 'OSMISS            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE MUSICOS                                                                                                                                                                                  ', 'siglas' => 'OSDEM             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE OBREROS EMPACADORES DE FRUTA  DE RIO NEGRO Y NEUQUEN                                                                                                                                     ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE OBREROS Y EMPLEADOS TINTOREROS SOMBREREROS Y LAVADEROS DE LA REPUBLICA ARGENTINA                                                                                                         ', 'siglas' => 'OSOETSYLARA       ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE PANADEROS, PASTELEROS Y FACTUREROS DE ENTRE RIOS                                                                                                                                         ', 'siglas' => 'OSSPYFER          ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE PATRONES DE CABOTAJE DE RIOS Y PUERTOS                                                                                                                                                   ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE PEONES DE TAXIS DE LA CAPITAL FEDERAL                                                                                                                                                    ', 'siglas' => 'OSPETAX           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE PETROLEROS                                                                                                                                                                               ', 'siglas' => 'OSPE              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE PETROLEROS DE CORDOBA                                                                                                                                                                    ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE PORTUARIOS ARGENTINOS                                                                                                                                                                    ', 'siglas' => 'OSPA              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE RECIBIDORES DE GRANOS Y ANEXOS                                                                                                                                                           ', 'siglas' => 'OSRGA             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE RELOJEROS Y JOYEROS                                                                                                                                                                      ', 'siglas' => 'OSRJA             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE SERENOS DE BUQUES                                                                                                                                                                        ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE TALLERISTAS A DOMICILIO                                                                                                                                                                  ', 'siglas' => 'OSTAD             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE TECNICOS DE FUTBOL                                                                                                                                                                       ', 'siglas' => 'OSTECF            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE TECNICOS DE VUELO DE LINEAS AEREAS                                                                                                                                                       ', 'siglas' => 'OSTVLA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE TRABAJADORES DE ESTACIONES DE SERVICIO                                                                                                                                                   ', 'siglas' => 'OSTES             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE TRABAJADORES DE LA INDUSTRIA DEL GAS                                                                                                                                                     ', 'siglas' => 'OSTIG             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE TRABAJADORES DE LAS COMUNICACIONES                                                                                                                                                       ', 'siglas' => 'OSTRAC            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE TRABAJADORES DE PERKINS ARGENTINA S.A.I.C                                                                                                                                                ', 'siglas' => 'OSTP              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE TRABAJADORES DE PRENSA DE BUENOS AIRES                                                                                                                                                   ', 'siglas' => 'OSTPBA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE TRABAJADORES VIALES Y AFINES DE LA REPUBLICA ARGENTINA                                                                                                                                   ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE VENDEDORES AMBULANTES DE LA REPUBLICA ARGENTINA                                                                                                                                          ', 'siglas' => 'OSVARA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE VIAJANTES VENDEDORES DE LA REPUBLICA ARGENTINA. (ANDAR)                                                                                                                                  ', 'siglas' => 'OSVVRA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DE YACIMIENTOS CARBONIFEROS                                                                                                                                                                 ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL ADMINISTRATIVO Y TECNICO DE LA CONSTRUCCION Y AFINES                                                                                                                           ', 'siglas' => 'OSPATCA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL AERONAUTICO                                                                                                                                                                    ', 'siglas' => 'OSPA              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL ASOCIADO A ASOCIACION MUTUAL SANCOR                                                                                                                                            ', 'siglas' => 'O.S.PERS.A.A.M.S. ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL AUXILIAR DE CASAS PARTICULARES                                                                                                                                                 ', 'siglas' => 'OSPACP            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL CINEMATOGRAFICO DE MAR DEL PLATA                                                                                                                                               ', 'siglas' => 'OSPERCIN          ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE  MICROS Y OMNIBUS DE MENDOZA                                                                                                                                                ', 'siglas' => 'OSPEMOM           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE AERONAVEGACION DE ENTES PRIVADOS                                                                                                                                            ', 'siglas' => 'OSPADEP           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE AGUAS GASEOSAS Y AFINES                                                                                                                                                     ', 'siglas' => 'OSPAGA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE BARRACAS DE LANAS, CUEROS Y ANEXOS                                                                                                                                          ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE CARGA Y DESCARGA                                                                                                                                                            ', 'siglas' => 'OSPCYD            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE CEMENTERIOS DE LA REPUBLICA ARGENTINA.                                                                                                                                      ', 'siglas' => 'OSPCRA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE CONSIGNATARIOS DEL MERCADO NACIONAL DE HACIENDA DE LINIERS                                                                                                                  ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA METALURGICA  Y DEMAS ACTIVIDADES EMPRESARIAS                                                                                                      ', 'siglas' => 'OSIM              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA INDUSTRIA PRIVADA DEL PETROLEO                                                                                                                              ', 'siglas' => 'OSDIPP            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LA SANIDAD LUIS PASTEUR                                                                                                                                        ', 'siglas' => 'OSLPASTEUR        ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LAS EMPRESAS DE LA ALIMENTACION Y DEMAS ACTIVIDADES EMPRESARIAS                                                                                                ', 'siglas' => 'OPDEA             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE DIRECCION DE LAS EMPRESAS QUE ACTUAN EN FRUTOS DEL PAIS                                                                                                                     ', 'siglas' => 'FRUTOS            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE DIRECCION DE PERFUMERIA E.W. HOPE                                                                                                                                           ', 'siglas' => 'WHOPE             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE DISTRIBUIDORAS CINEMATOGRAFICAS                                                                                                                                             ', 'siglas' => 'OSPEDICI          ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE EDIFICIOS DE RENTA Y HORIZONTAL DE LA CIUDAD AUTONOMA DE BUENOS AIRES  Y GRAN BUENOS AIRES                                                                                  ', 'siglas' => 'OSPERYH           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE EMPRESAS FIAT Y EMPRESAS PEUGEOT CITROEN ARGENTINA                                                                                                                          ', 'siglas' => 'OSPEF Y EPCA      ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE ESCRIBANIAS DE LA PROVINCIA DE BUENOS AIRES                                                                                                                                 ', 'siglas' => 'OSPEPBA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE ESCRIBANOS                                                                                                                                                                  ', 'siglas' => 'OSPE              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS DE ESTACIONAMIENTO Y LAVADEROS AUTOMATICOS                                                                                          ', 'siglas' => 'OSPESGYPE         ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE ESTACIONES DE SERVICIO, GARAJES, PLAYAS Y LAVADEROS AUTOMATICOS DE LA PROVINCIA DE SANTA FE                                                                                 ', 'siglas' => 'OSPESGA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE FABRICAS DE PINTURA                                                                                                                                                         ', 'siglas' => 'UPFPARA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE FARMACIA                                                                                                                                                                    ', 'siglas' => 'OSPF              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE IMPRENTA, DIARIOS Y AFINES                                                                                                                                                  ', 'siglas' => 'OSPIDA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE INDUSTRIAS QUIMICAS Y PETROQUIMICAS                                                                                                                                         ', 'siglas' => 'OSPIQYP           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE INSTALACIONES SANITARIAS                                                                                                                                                    ', 'siglas' => 'OSPIS             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE JABONEROS                                                                                                                                                                   ', 'siglas' => 'OSPEJ             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD CERVECERA Y AFINES                                                                                                                                             ', 'siglas' => 'OSPACA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD DEL TURF                                                                                                                                                       ', 'siglas' => 'OSPAT             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD FRUTICOLA                                                                                                                                                      ', 'siglas' => 'OSPAF             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD VITIVINICOLA                                                                                                                                                   ', 'siglas' => 'OSPAV             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA CERAMICA, SANITARIOS, PORCELANA DE MESA Y AFINES                                                                                                                         ', 'siglas' => 'OSPCSPMYA         ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA CONSTRUCCION                                                                                                                                                             ', 'siglas' => 'OSPECON           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA CONSTRUCCION                                                                                                                                                             ', 'siglas' => 'OSPECON           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA EMPRESA NACIONAL DE CORREOS Y TELEGRAFOS S.A. Y DE LAS  COMUNICACIONES DE LA REPULICA ARGENTINA                                                                          ', 'siglas' => 'OSPEC             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA ENSE¥ANZA PRIVADA                                                                                                                                                        ', 'siglas' => 'OSPEP             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA  DEL TABACO                                                                                                                                                    ', 'siglas' => 'OSPIT             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA AZUCARERA                                                                                                                                                      ', 'siglas' => 'OSPIA             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA BOTONERA                                                                                                                                                       ', 'siglas' => 'OSPIB             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA CINEMATOGRAFICA                                                                                                                                                ', 'siglas' => 'OSPIC             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DE LA ALIMENTACION                                                                                                                                             ', 'siglas' => 'OSPIA             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CALZADO                                                                                                                                                    ', 'siglas' => 'OSPICAL           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CAUCHO                                                                                                                                                     ', 'siglas' => 'OSPIC             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL CUERO Y AFINES                                                                                                                                             ', 'siglas' => 'OSPICA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL FIBROCEMENTO                                                                                                                                               ', 'siglas' => 'OSPIF             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL FOSFORO, ENCENDIDO Y AFINES                                                                                                                                ', 'siglas' => 'OSPIF             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL HIELO Y MERCADOS PARTICULARES                                                                                                                              ', 'siglas' => 'OSPIHMP           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL NEUMATICO                                                                                                                                                  ', 'siglas' => 'OSPIN             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL PLASTICO                                                                                                                                                   ', 'siglas' => 'OSPIP             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL TRACTOR                                                                                                                                                    ', 'siglas' => 'OSPIT             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VESTIDO                                                                                                                                                    ', 'siglas' => 'OSPIV             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA DEL VIDRIO                                                                                                                                                     ', 'siglas' => 'OSPIV             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA FIDEERA                                                                                                                                                        ', 'siglas' => 'OSPIF             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA FORESTAL DE SANTIAGO DEL ESTERO                                                                                                                                ', 'siglas' => 'OSPIFSE           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA GRAFICA DE LA PROVINCIA DE CORDOBA                                                                                                                             ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LADRILLERA A MAQUINA                                                                                                                                           ', 'siglas' => 'OSPILM            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA LECHERA                                                                                                                                                        ', 'siglas' => 'OSPIL             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MADERERA                                                                                                                                                       ', 'siglas' => 'OSPIM             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA MOLINERA                                                                                                                                                       ', 'siglas' => 'OSPIM             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA NAVAL                                                                                                                                                          ', 'siglas' => 'OSPIN             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA PETROQUIMICA                                                                                                                                                   ', 'siglas' => 'OSPIP             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA INDUSTRIA TEXTIL                                                                                                                                                         ', 'siglas' => 'OSPIT             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA PUBLICIDAD                                                                                                                                                               ', 'siglas' => 'OSPP              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LA SANIDAD ARGENTINA                                                                                                                                                        ', 'siglas' => 'OSPSA             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE LAS TELECOMUNICACIONES DE LA REPUBLICA ARGENTINA                                                                                                                            ', 'siglas' => 'OSTEL             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE MAESTRANZA                                                                                                                                                                  ', 'siglas' => 'OSPM              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE MANIPULEO, EMPAQUE Y EXPEDICION DE FRUTA FRESCA Y HORTALIZAS DE CUYO                                                                                                        ', 'siglas' => 'OSFYHC            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PANADERIAS                                                                                                                                                                  ', 'siglas' => 'OSPEP             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PBBPOLISUR  SA  DE  BAHIA BLANCA                                                                                                                                            ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PELUQUERIAS, ESTETICAS Y AFINES                                                                                                                                             ', 'siglas' => 'OSPPEA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE BAHIA BLANCA                                                                                                                                                      ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE LA PROVINCIA DE CHACO                                                                                                                                             ', 'siglas' => 'OSPPCHA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE LA REPUBLICA ARGENTINA                                                                                                                                            ', 'siglas' => 'OSPPRA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE MAR DEL PLATA                                                                                                                                                     ', 'siglas' => 'OSPREN            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE MENDOZA                                                                                                                                                           ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE ROSARIO                                                                                                                                                           ', 'siglas' => 'OSPRO             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE TUCUMAN                                                                                                                                                           ', 'siglas' => 'OSPRENTUC         ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE RECOLECCION Y BARRIDO DE ROSARIO                                                                                                                                            ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE REFINERIAS DE MAIZ                                                                                                                                                          ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE SEGURIDAD COMERCIAL, INDUSTRIAL E INVESTIGACIONES PRIVADAS                                                                                                                  ', 'siglas' => 'OSPSIP            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE SOCIEDADES DE AUTORES Y AFINES                                                                                                                                              ', 'siglas' => 'OSPESA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE TELEVISION                                                                                                                                                                  ', 'siglas' => 'OSPTV             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DE VIGILANCIA Y SEGURIDAD COMERCIAL, INDUSTRIAL E INVESTIGACIONES PRIVADAS DE CORDOBA                                                                                          ', 'siglas' => 'OSPEVIC           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DEL AUTOMOVIL  CLUB ARGENTINO                                                                                                                                                  ', 'siglas' => 'OSPACA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DEL AZUCAR DEL INGENIO RIO GRANDE                                                                                                                                              ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DEL ESPECTACULO PUBLICO                                                                                                                                                        ', 'siglas' => 'OSPEP             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DEL ORGANISMO DE CONTROL EXTERNO                                                                                                                                               ', 'siglas' => 'OSPOCE            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DEL PAPEL, CARTON Y QUIMICOS                                                                                                                                                   ', 'siglas' => 'OSPPCYQ           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DEL TURISMO, HOTELERO Y GASTRONOMICO DE LA UNION  DE TRABAJADORES  DEL TURISMO HOTELEROS Y GASTRONOMICOS DE LA REPUBLICA  ARGENTINA                                            ', 'siglas' => 'OSUTHGRA          ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL DIRECTIVO DE LA INDUSTRIA DE LA CONSTRUCCION                                                                                                                                   ', 'siglas' => 'OSDIC             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL GRAFICO                                                                                                                                                                        ', 'siglas' => 'OSPG              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL JERARQUICO DE LA REPUBLICA ARGENTINA PARA EL PERSONAL JERARQUICO DE LA INDUSTRIA GRAFICA Y EL PERSONAL JERARQUICO DEL AGUA Y LA ENERGIA                                        ', 'siglas' => 'OSJERA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL JERARQUICO DEL TRANSPORTE AUTOMOTOR DE PASAJEROS DE CORDOBA Y AFINES                                                                                                           ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL LADRILLERO                                                                                                                                                                     ', 'siglas' => 'OSPL              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL MARITIMO                                                                                                                                                                       ', 'siglas' => 'OSPM              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL MENSUALIZADO DEL JOCKEY CLUB DE BUENOS AIRES Y LOS HIPODROMOS DE PALERMO Y SAN ISIDRO                                                                                          ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL MOSAISTA                                                                                                                                                                       ', 'siglas' => 'OSPM              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL MUNICIPAL DE AVELLANEDA                                                                                                                                                        ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL MUNICIPAL DE LA MATANZA                                                                                                                                                        ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL NAVAL                                                                                                                                                                          ', 'siglas' => 'OSPENA            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL RURAL Y ESTIBADORES DE LA REPUBLICA ARGENTINA                                                                                                                                  ', 'siglas' => 'OSPRERA           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL SUPERIOR MERCEDES BENZ ARGENTINA                                                                                                                                               ', 'siglas' => 'OSPS MERCEDES     ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PERSONAL TECNICO AERONAUTICO                                                                                                                                                            ', 'siglas' => 'OSPTA             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL PETROLEO Y GAS PRIVADO                                                                                                                                                                  ', 'siglas' => 'OSPEGAP           ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL DEL SINDICATO UNIDO DE TRABAJADORES DE LA INDUSTRIA DE AGUAS GASEOSAS DE LA PROVINCIA DE SANTA FE                                                                                           ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL ELECTRICISTAS NAVALES                                                                                                                                                                       ', 'siglas' => 'OSEN              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL FEDERAL DE LA FEDERACION NACIONAL DE TRABAJADORES DE OBRAS SANITARIAS                                                                                                                       ', 'siglas' => 'OSFFENTOS         ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL FEDERAL DE LA FEDERACION NACIONAL DE TRABAJADORES DE OBRAS SANITARIAS                                                                                                                       ', 'siglas' => 'OSFFENTOS         ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL FERROVIARIA                                                                                                                                                                                 ', 'siglas' => 'OSFE              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL MODELOS ARGENTINOS                                                                                                                                                                          ', 'siglas' => 'OSMA              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA EL  PERSONAL MUNICIPAL DE TRES DE FEBRERO                                                                                                                                              ', 'siglas' => '                  ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA EL PERSONAL DE DIRECCION DE LA INDUSTRIA MADERERA                                                                                                                                      ', 'siglas' => 'OSMAD             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA EL PERSONAL DE ESTACIONES DE SERVICIO, GARAGES, PLAYAS DE ESTACIONAMIENTO, LAVADEROS AUTOMATICOS Y GOMERIAS DE LA REPUBLICA ARGENTINA                                                  ', 'siglas' => 'OSPES             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA EL PERSONAL DE LA INDUSTRIA ACEITERA, DESMOTADORA Y AFINES                                                                                                                             ', 'siglas' => 'OSIAD             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA EL PERSONAL DE LA INDUSTRIA ACEITERA, DESMOTADORA Y AFINES                                                                                                                             ', 'siglas' => 'OSIAD             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA EL PERSONAL DE OBRAS Y SERVICIOS SANITARIOS                                                                                                                                            ', 'siglas' => 'OSOSS             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA EL PERSONAL DEL MINISTERIO DE ECONOMIA Y DE OBRAS Y SERVICIOS PUBLICOS                                                                                                                 ', 'siglas' => 'OSME              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA LA ACTIVIDAD DOCENTE                                                                                                                                                                   ', 'siglas' => 'OSPLAD            ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA LOS TRABAJADORES DE LA EDUCACION PRIVADA                                                                                                                                               ', 'siglas' => 'OSTEP             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PARA PILOTOS DE LINEAS AEREAS COMERCIALES Y REGULARES                                                                                                                                       ', 'siglas' => 'OSPLA             ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PERSONAL ESTACIONES DE SERVICIO,GARAGES,PLAYAS Y LAVADEROS DE LA PROVINCIA DEL CHACO                                                                                                        ', 'siglas' => 'OSPESCHA          ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PORTUARIOS ARGENTINOS DE MAR DEL PLATA                                                                                                                                                      ', 'siglas' => 'OSPA              ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL PROFESIONALES DEL TURF DE LA REPUBLICA ARGENTINA                                                                                                                                            ', 'siglas' => 'OSPROTURA         ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL TRABAJADORES  PASTELEROS, CONFITEROS, PIZZEROS , HELADEROS Y ALFAJOREROS DE LA REPUBLICA ARGENTINA                                                                                          ', 'siglas' => 'OSTPCHPYARA       ' ]);
      ObraSocial::create([ 'nombre' => 'OBRA SOCIAL UNION PERSONAL DE LA UNION DEL  PERSONAL CIVIL DE LA NACION                                                                                                                                 ', 'siglas' => 'OSPCN             ' ]);
      

      


    }
}
